version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_DATABASE: pokedex
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
